version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find .
      - run: cd src/src
      - run: ls -l
      - run: dotnet restore
      - run: dotnet build